<h1>Recently Viewed Products</h1>

<?php
$col = $this->getRecentlyviewedcol();
$count = count($col);
$_productloader = $this->getProductLoader();
?>
    
<?php if($count): ?>         
    <div class="wishtlist-recently-viewed">
        <div class="d-recently-title">
            <h3>Recently Viewed</h3>
        </div>
        <div class="d-view-blocks">
            <ul>
                <?php foreach ($col as $item) : ?> 
                    <?php        
                        $loadedProduct = $_productloader->create()->load($item->getEntityId());
                        $i = $this->helper('Magento\Catalog\Helper\Image')->init($loadedProduct, 'product_page_image_large'); 
                    ?>
                <li class="col-12 col-lg-3 col-md-3 col-sm-12">
                    <div class="d-slide-box">
                        <div class="d-block-div ">
                            <div class="d-wishlist-img">
                                <a href="<?=$loadedProduct->getProductUrl();?>"><img style="width:300px;height:350px;" class="img-fluid" src="<?=$i->getUrl();?>" alt="First slide"></a>
                            </div>
                            <div class="d-view-title-inner d-view-title-inner-r-v">
                            <div class="d-wishlist-title">
                                <a href="<?=$loadedProduct->getProductUrl();?>"><h3><?=$loadedProduct->getName()?></h3></a>
                            </div>

                            </div>

                        </div>
                    </div>
                </li>

                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif;?>
